package com.iflytek.astron.console.toolkit.util.ssrf;

import lombok.Data;

import java.util.*;

/**
 * Configuration properties for SSRF (Server-Side Request Forgery) protection.
 *
 * <p>
 * This class defines key rules such as IP blacklists, allowed schemes, subdomain handling, private
 * network blocking, and redirect validation.
 * </p>
 *
 * <p>
 * Getter, setter, equals, hashCode, and toString methods are generated by Lombok {@code @Data}.
 * </p>
 *
 * <p>
 * Thread safety: Instances of this class are not immutable. They should be treated as configuration
 * holders and used in a read-only way at runtime.
 * </p>
 *
 * @author clliu19
 */
@Data
public class SsrfProperties {

    /**
     * List of blocked IPs or hostnames.
     *
     * <p>
     * Used to explicitly reject requests to dangerous or restricted addresses.
     * </p>
     */
    private List<String> ipBlaklist = new ArrayList<>();

    /**
     * Allowed URL schemes.
     *
     * <p>
     * Default includes {@code http}, {@code https}, {@code ws}, and {@code wss}.
     * </p>
     */
    private Set<String> allowedSchemes = new HashSet<>(Arrays.asList("http", "https", "ws", "wss"));

    /**
     * Allowed ports.
     *
     * <p>
     * Currently disabled; historically used to restrict allowed ports (e.g., 80, 443).
     * </p>
     */
    // private Set<Integer> allowedPorts = new HashSet<>(Arrays.asList(80, 443));

    /**
     * Whether to allow subdomains of whitelisted domains.
     *
     * <p>
     * For example, if {@code iflytek.com} is whitelisted, this controls whether {@code *.iflytek.com}
     * should also be allowed.
     * </p>
     */
    private boolean allowSubdomains = true;

    /**
     * Whether to strictly block private network, loopback, link-local, multicast, or reserved
     * addresses.
     *
     * <p>
     * Default is {@code true} for security reasons.
     * </p>
     */
    private boolean blockPrivate = true;

    /**
     * Whether to revalidate each hop during HTTP redirect following.
     *
     * <p>
     * Recommended to keep as {@code true} to prevent bypass through redirects.
     * </p>
     */
    private boolean validateOnRedirect = true;
}
