"""Otlp related constant keys."""

SERVICE_NAME_KEY = "SERVICE_NAME"
OTLP_ENABLE_KEY = "OTLP_ENABLE"
OTLP_DC_KEY = "OTLP_DC"
OTLP_SERVICE_NAME_KEY = "OTLP_SERVICE_NAME"
KAFKA_TOPIC_KEY = "KAFKA_TOPIC"
