SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `chat_bot_base`;
CREATE TABLE `chat_bot_base` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'bot_id',
  `uid` varchar(128) DEFAULT NULL COMMENT 'User ID',
  `bot_name` varchar(48) DEFAULT NULL COMMENT 'Bot name',
  `bot_type` tinyint DEFAULT NULL COMMENT 'Bot type: 1 Custom Assistant, 2 Life Assistant, 3 Workplace Assistant, 4 Marketing Assistant, 5 Writing Expert, 6 Knowledge Expert',
  `avatar` varchar(1024) DEFAULT NULL COMMENT 'Bot avatar',
  `pc_background` varchar(512) DEFAULT '' COMMENT 'PC chat background image',
  `app_background` varchar(512) DEFAULT '' COMMENT 'Mobile chat background image',
  `background_color` tinyint DEFAULT '0' COMMENT 'Background image color depth: 0 Light, 1 Dark',
  `prompt` varchar(2048) DEFAULT NULL COMMENT 'bot_prompt',
  `prologue` varchar(512) DEFAULT NULL COMMENT 'Opening statement',
  `bot_desc` varchar(255) DEFAULT NULL COMMENT 'Bot description',
  `is_delete` tinyint DEFAULT '0' COMMENT 'Whether deleted: 0 Not deleted, 1 Deleted',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  `support_context` tinyint NOT NULL DEFAULT '0' COMMENT 'Whether to support multi-turn conversation: 1 Support, 0 Not support',
  `bot_template` varchar(255) DEFAULT '' COMMENT 'Input template',
  `prompt_type` tinyint UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Instruction type: 0 Regular (custom instruction), 1 Structured instruction',
  `input_example` varchar(600) DEFAULT '' COMMENT 'Input example',
  `botweb_status` tinyint NOT NULL DEFAULT '0' COMMENT 'Whether to open independent assistant application: 0 Closed, 1 Opened',
  `version` int DEFAULT '1' COMMENT 'Assistant version number',
  `support_document` tinyint DEFAULT '0' COMMENT 'Whether to support files: 0 Not support, 1 Strictly based on documents, 2 Can provide divergent answers',
  `support_system` tinyint DEFAULT '0' COMMENT 'Whether to support system instructions: 0 Not support, 1 Support',
  `prompt_system` tinyint DEFAULT '0' COMMENT 'System instruction status',
  `support_upload` tinyint NOT NULL DEFAULT '0' COMMENT 'Whether to support document upload: 0 Not support, 1 Support',
  `bot_name_en` varchar(48) DEFAULT NULL COMMENT 'Assistant name (English version)',
  `bot_desc_en` varchar(500) DEFAULT NULL COMMENT 'Assistant description (English version)',
  `client_type` tinyint NOT NULL DEFAULT '0' COMMENT 'Client type',
  `vcn_cn` varchar(32) DEFAULT NULL COMMENT 'Chinese voice talent',
  `vcn_en` varchar(32) DEFAULT NULL COMMENT 'English voice talent',
  `vcn_speed` tinyint NOT NULL DEFAULT '50' COMMENT 'Voice talent speaking speed',
  `is_sentence` tinyint NOT NULL DEFAULT '0' COMMENT 'Whether generated in one sentence: 0 No, 1 Yes',
  `opened_tool` varchar(128) DEFAULT 'ifly_search,text_to_image,codeinterpreter' COMMENT 'Enabled tools, joined by commas',
  `client_hide` varchar(10) DEFAULT '' COMMENT 'Hidden on certain clients',
  `virtual_bot_type` tinyint DEFAULT NULL COMMENT 'Virtual personality type',
  `virtual_agent_id` bigint DEFAULT NULL COMMENT 'virtual_agent_list primary key',
  `style` int DEFAULT NULL COMMENT 'Style type: 0 Original, 1 Business Elite, 2 Casual Moment',
  `background` varchar(512) DEFAULT NULL COMMENT 'Background settings',
  `virtual_character` varchar(512) DEFAULT NULL COMMENT 'Character setting',
  `model` varchar(32) DEFAULT 'spark' COMMENT 'Model selected by assistant',
  `maas_bot_id` varchar(50) DEFAULT NULL COMMENT 'maas_bot_id',
  `prologue_en` varchar(1024) DEFAULT NULL COMMENT 'Opening statement - English',
  `input_example_en` varchar(1024) DEFAULT NULL COMMENT 'Recommended questions - English',
  `space_id` bigint DEFAULT NULL COMMENT 'Space ID',
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_support_context` (`support_context`),
  KEY `idx_uid` (`uid`),
  KEY `idx_botweb_status` (`botweb_status`),
  KEY `idx_space_id` (`space_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='User created assistant table';

SET FOREIGN_KEY_CHECKS = 1;