CREATE TABLE xingchen_prompt_manage (
    id bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key ID',
    mongodb_id varchar(50) NOT NULL COMMENT 'MongoDB original _id',
    name varchar(500) NOT NULL COMMENT 'Prompt name',
    prompt_key varchar(255) NOT NULL COMMENT 'Prompt unique identifier key',
    uid varchar(128) NOT NULL COMMENT 'User ID',
    type tinyint NOT NULL DEFAULT 0 COMMENT 'Prompt type',
    latest_version varchar(50) DEFAULT '' COMMENT 'Latest version number',
    current_version varchar(50) DEFAULT '' COMMENT 'Current version number',
    model_config json NOT NULL COMMENT 'Model configuration information (JSON format)',
    prompt_text json NOT NULL COMMENT 'Prompt text content (JSON format)',
    prompt_input json NOT NULL COMMENT 'Prompt input variable configuration (JSON format)',
    status tinyint NOT NULL DEFAULT 0 COMMENT 'Status: 0-Normal, 1-Disabled',
    is_delete tinyint NOT NULL DEFAULT 0 COMMENT 'Whether deleted: 0-No, 1-Yes',
    commit_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Commit time',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    PRIMARY KEY (id),
    UNIQUE KEY uk_mongodb_id (mongodb_id),
    UNIQUE KEY uk_prompt_key_uid (prompt_key, uid),
    KEY idx_uid (uid),
    KEY idx_type (type),
    KEY idx_status (status),
    KEY idx_latest_version (latest_version),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Astron Prompt management table';