CREATE TABLE xingchen_prompt_version (
    id bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key ID',
    mongodb_id varchar(50) NOT NULL COMMENT 'MongoDB original _id',
    prompt_id varchar(50) NOT NULL COMMENT 'Associated prompt ID',
    uid varchar(128) NOT NULL COMMENT 'User ID',
    version varchar(50) NOT NULL COMMENT 'Version number',
    version_desc text COMMENT 'Version description',
    commit_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Commit time',
    commit_user varchar(128) NOT NULL COMMENT 'Commit user ID',
    model_config json NOT NULL COMMENT 'Model configuration information (JSON format)',
    prompt_text json NOT NULL COMMENT 'Prompt text content (JSON format)',
    prompt_input json NOT NULL COMMENT 'Prompt input variable configuration (JSON format)',
    is_delete tinyint NOT NULL DEFAULT 0 COMMENT 'Whether deleted: 0-No, 1-Yes',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    PRIMARY KEY (id),
    UNIQUE KEY uk_mongodb_id (mongodb_id),
    KEY idx_prompt_id (prompt_id),
    KEY idx_uid (uid),
    KEY idx_version (version),
    KEY idx_commit_user (commit_user),
    KEY idx_commit_time (commit_time),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Stellar Prompt version management table';