# Common general configuration
# Blacklist configuration
SEGMENT_BLACK_LIST_KEY = "SEGMENT_BLACK_LIST"
IP_BLACK_LIST_KEY = "IP_BLACK_LIST"
DOMAIN_BLACK_LIST_KEY = "DOMAIN_BLACK_LIST"
# Distinguish between official and third-party tools
OFFICIAL_TOOL_KEY = "OFFICIAL_TOOL"
THIRD_TOOL_KEY = "THIRD_TOOL"
# Official default app ID
DEFAULT_APPID_KEY = "DEFAULT_APPID"
# ID generation
DATACENTER_ID_KEY = "DATACENTER_ID"
WORKER_ID_KEY = "WORKER_ID"

HTTP_AUTH_QU_APP_ID_KEY = "HTTP_AUTH_QU_APP_ID"
HTTP_AUTH_QU_APP_KEY_KEY = "HTTP_AUTH_QU_APP_KEY"
HTTP_AUTH_AWAU_APP_ID_KEY = "HTTP_AUTH_AWAU_APP_ID"
HTTP_AUTH_AWAU_API_KEY_KEY = "HTTP_AUTH_AWAU_API_KEY"
HTTP_AUTH_AWAU_API_SECRET_KEY = "HTTP_AUTH_AWAU_API_SECRET"
