# Spark link log configuration

LOG_LEVEL_KEY = "LOG_LEVEL"
LOG_PATH_KEY = "LOG_PATH"

PROJECT_NAME_KEY = "PROJECT_NAME"
VERSION_KEY = "VERSION"
CONFIG_FILE_KEY = "CONFIG_FILE"
ENVIRONMENT_KEY = "ENVIRONMENT"

POLARIS_URL_KEY = "POLARIS_URL"
POLARIS_CLUSTER_KEY = "POLARIS_CLUSTER"
POLARIS_USERNAME_KEY = "POLARIS_USERNAME"
POLARIS_PASSWORD_KEY = "POLARIS_PASSWORD"
