# uvicorn
UVICORN_HOST_KEY = "UVICORN_HOST"
UVICORN_PORT_KEY = "UVICORN_PORT"
UVICORN_WORKERS_KEY = "UVICORN_WORKERS"
UVICORN_RELOAD_KEY = "UVICORN_RELOAD"
UVICORN_WS_PING_INTERVAL_KEY = "UVICORN_WS_PING_INTERVAL"
UVICORN_WS_PING_TIMEOUT_KEY = "UVICORN_WS_PING_TIMEOUT"
