"""XIAOWU RPA related constant keys."""

XIAOWU_RPA_TIMEOUT_KEY = "XIAOWU_RPA_TIMEOUT"
XIAOWU_RPA_PING_INTERVAL_KEY = "XIAOWU_RPA_PING_INTERVAL"
XIAOWU_RPA_TASK_QUERY_INTERVAL_KEY = "XIAOWU_RPA_TASK_QUERY_INTERVAL"
XIAOWU_RPA_TASK_CREATE_URL_KEY = "XIAOWU_RPA_TASK_CREATE_URL"
XIAOWU_RPA_TASK_QUERY_URL_KEY = "XIAOWU_RPA_TASK_QUERY_URL"
